### ISSUE TITLE
Non existing file passed to compiler

### ISSUE THREAD

**Issue by laeubi** [eclipse/tycho#1197]
```
21:46:43  [INFO] --- tycho-compiler-plugin:3.0.0-SNAPSHOT:compile (default-compile) @ org.eclipse.pde.unittest.junit ---
21:46:43  [INFO] Compiling 8 source files to /home/jenkins/agent/workspace/eclipse.pde.ui_master/ui/org.eclipse.pde.unittest.junit/target/classes
21:46:43  Failed to init Classpath for jar file /home/jenkins/agent/workspace/eclipse.pde.ui_master/.m2/repository/org/ow2/sat4j/org.ow2.sat4j.pb/2.3.6/org.sat4j.core.jar
21:46:43  java.nio.file.NoSuchFileException: /home/jenkins/agent/workspace/eclipse.pde.ui_master/.m2/repository/org/ow2/sat4j/org.ow2.sat4j.pb/2.3.6/org.sat4j.core.jar
21:46:43  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
21:46:43  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
21:46:43  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
21:46:43  	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
21:46:43  	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
21:46:43  	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
21:46:43  	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
21:46:43  	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
21:46:43  	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
21:46:43  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
21:46:43  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
21:46:43  	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
21:46:43  	at org.eclipse.jdt.internal.compiler.batch.ClasspathJar.initialize(ClasspathJar.java:201)
21:46:43  	at org.eclipse.jdt.internal.compiler.batch.FileSystem.<init>(FileSystem.java:235)
21:46:43  	at org.eclipse.jdt.internal.compiler.batch.Main.getLibraryAccess(Main.java:3495)
21:46:43  	at org.eclipse.jdt.internal.compiler.batch.Main.performCompilation(Main.java:4741)
21:46:43  	at org.eclipse.jdt.internal.compiler.batch.Main.compile(Main.java:1802)
21:46:43  	at org.eclipse.tycho.compiler.jdt.JDTCompiler.compileInProcess(JDTCompiler.java:370)
21:46:43  	at org.eclipse.tycho.compiler.jdt.JDTCompiler.performCompile(JDTCompiler.java:123)
21:46:43  	at copied.org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:414)
21:46:43  	at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.doCompile(AbstractOsgiCompilerMojo.java:370)
21:46:43  	at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.execute(AbstractOsgiCompilerMojo.java:351)
21:46:43  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
21:46:43  	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:301)
21:46:43  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:211)
21:46:43  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:165)
21:46:43  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)
21:46:43  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
21:46:43  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
21:46:43  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
21:46:43  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:127)
21:46:43  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
21:46:43  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
21:46:43  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
21:46:43  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
21:46:43  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
21:46:43  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
21:46:43  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:46:43  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
21:46:43  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:46:43  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
21:46:43  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
21:46:43  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
21:46:43  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
21:46:43  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Comment by laeubi** [comment]
Not a Tycho issue see:

- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/261
