### ISSUE TITLE
running surefire JUnit5 tests causes warning: TestEngine with ID 'junit-vintage' failed to discover tests

### ISSUE THREAD

**Issue by Pontesegger** [eclipse/tycho#134]
When running surefire tests for JUnit 5 tests I get following warning:

`WARNING: TestEngine with ID 'junit-vintage' failed to discover tests`
`java.lang.NoClassDefFoundError: org/junit/runners/model/RunnerBuilder`
`12:15:25  	at org.junit.vintage.engine.discovery.VintageDiscoverer.<init>(VintageDiscoverer.java:48)`
`12:15:25  	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:65)#`
'...'

While the tests do work all logs get flooded by tons of stacktraces for this warning.

I tried to use a provider hint, but that does not resolve the issue:
`			<plugin>`
`				<groupId>org.eclipse.tycho</groupId>`
`				<artifactId>tycho-surefire-plugin</artifactId>`
`				<version>2.2.0</version>`
`				<configuration>`
`					<providerHint>junit5</providerHint>`
`				</configuration>`
`			</plugin>`

Expectation: no warning/stacktrace printed to console

**Comment by laeubi** [comment]
@Pontesegger what version of tycho you are using? Can you provide a reproducer that shows the problem?

**Comment by Pontesegger** [comment]
Tycho version is available from the pom content: 2.2.0.
A build showing the problem is available here: https://ci.eclipse.org/ease/job/ease.build.core/

To reproduce locally run:
`git clone "git://git.eclipse.org/gitroot/ease/org.eclipse.ease.core"`
`cd org.eclipse.ease.core`
'mvn clean verify'

**Comment by mickaelistria** [comment]
Can you please try Tycho 2.3.0 and report whether things are better/worse/same?

**Comment by Pontesegger** [comment]
Same issue on 2.3.0

**Comment by mickaelistria** [comment]
@Pontesegger Can you please try to reduce the erroneous case to a minimal reproducer?

**Comment by Pontesegger** [comment]
@mickaelistria take my previous example, then modify 'releng/org.eclipse.ease.releng/pom.xml'. Search the modules section and keep only following modules:
              <module>../../plugins/org.eclipse.ease</module>
                <module>../../plugins/org.eclipse.ease.ui</module>
                <module>../org.eclipse.ease.releng.target</module>
                <module>../../tests/org.eclipse.ease.ui.test</module>

then run maven

**Comment by mickaelistria** [comment]
To be honest, that's more than what I'm ready to invest at the moment. I'm looking for a basic single-module almost empty reproducer that we can easily debug and copy into the test suites. Trimming a whole project tree and keeping 4-modules is too.much.
