### ISSUE TITLE
M2E-core build fails with Uses-constraint-violations

### ISSUE THREAD

**Issue by HannesWell** [eclipse/tycho#303]
The Maven build of m2e-core fails when the latest Tycho 2.5.0-SNAPSHOT is used because the resolution of the Target-Platform fails because of `org.apache.felix.resolver.reason.ReasonException: Uses constraint violations`.

A draft PR in m2e outlines this issue: https://github.com/eclipse-m2e/m2e-core/pull/334:

```
[INFO] Fetching org.w3c.dom.smil_1.0.1.v200903091627.jar from https://download.eclipse.org/eclipse/updates/4.21/R-4.21-202109060500/plugins/ (21.24kB)
[ERROR] Internal error: java.lang.RuntimeException: org.osgi.framework.BundleException: Bundle org.eclipse.m2e.core.ui cannot be resolved:org.eclipse.m2e.core.ui [115]
[ERROR]   Unresolved requirement: Require-Bundle: org.eclipse.m2e.model.edit; bundle-version="[1.16.0,2.0.0)"; visibility:="reexport"
[ERROR]     -> Bundle-SymbolicName: org.eclipse.m2e.model.edit; bundle-version="1.18.2.qualifier"; singleton:="true"
[ERROR]        org.eclipse.m2e.model.edit [116]
[ERROR]          Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
[ERROR]            -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.300.v202102110535"; singleton:="true"
[ERROR]               org.eclipse.wst.xml.core [105]
[ERROR]                 Unresolved requirement: Require-Bundle: org.eclipse.jem.util; bundle-version="[2.1.200,3.0.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Require-Bundle: org.eclipse.wst.validation; bundle-version="[1.2.700,1.3.0)"; resolution:="optional"
[ERROR]                 Unresolved requirement: Require-Bundle: org.eclipse.wst.common.emfworkbench.integration; bundle-version="[1.2.100,1.3.0)"; resolution:="optional"
[ERROR]                 Bundle was not resolved because of a uses constraint violation.
[ERROR]   org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"] because it is exposed to package 'org.w3c.dom.events' from resources org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"] and org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"] via two dependency chains.
[ERROR] 
[ERROR] Chain 1:
[ERROR]   org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
[ERROR]     require: (&(osgi.wiring.bundle=org.eclipse.core.runtime)(&(bundle-version>=3.14.0)(!(bundle-version>=4.0.0))))
[ERROR]      |
[ERROR]     provide: osgi.wiring.bundle: org.eclipse.core.runtime
[ERROR]   org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"]
[ERROR] 
[ERROR] Chain 2:
[ERROR]   org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
[ERROR]     require: (&(osgi.wiring.bundle=org.apache.xerces)(&(bundle-version>=2.12.1)(!(bundle-version>=3.0.0))))
[ERROR]      |
[ERROR]     provide: osgi.wiring.bundle; bundle-version:Version="2.12.1.v20210115-0812"; osgi.wiring.bundle="org.apache.xerces"
[ERROR]   org.apache.xerces [osgi.identity; osgi.identity="org.apache.xerces"; type="osgi.bundle"; version:Version="2.12.1.v20210115-0812"]
[ERROR]     import: (osgi.wiring.package=org.w3c.dom.events)
[ERROR]      |
[ERROR]     export: osgi.wiring.package: org.w3c.dom.events
[ERROR]   org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"]
[ERROR] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.osgi.framework.BundleException: Bundle org.eclipse.m2e.core.ui cannot be resolved:org.eclipse.m2e.core.ui [115]
  Unresolved requirement: Require-Bundle: org.eclipse.m2e.model.edit; bundle-version="[1.16.0,2.0.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.m2e.model.edit; bundle-version="1.18.2.qualifier"; singleton:="true"
       org.eclipse.m2e.model.edit [116]
         Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.300.v202102110535"; singleton:="true"
              org.eclipse.wst.xml.core [105]
                Unresolved requirement: Require-Bundle: org.eclipse.jem.util; bundle-version="[2.1.200,3.0.0)"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.wst.validation; bundle-version="[1.2.700,1.3.0)"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.wst.common.emfworkbench.integration; bundle-version="[1.2.100,1.3.0)"; resolution:="optional"
                Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"] because it is exposed to package 'org.w3c.dom.events' from resources org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"] and org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"] via two dependency chains.

Chain 1:
  org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.eclipse.core.runtime)(&(bundle-version>=3.14.0)(!(bundle-version>=4.0.0))))
     |
    provide: osgi.wiring.bundle: org.eclipse.core.runtime
  org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"]

Chain 2:
  org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.apache.xerces)(&(bundle-version>=2.12.1)(!(bundle-version>=3.0.0))))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="2.12.1.v20210115-0812"; osgi.wiring.bundle="org.apache.xerces"
  org.apache.xerces [osgi.identity; osgi.identity="org.apache.xerces"; type="osgi.bundle"; version:Version="2.12.1.v20210115-0812"]
    import: (osgi.wiring.package=org.w3c.dom.events)
     |
    export: osgi.wiring.package: org.w3c.dom.events
  org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"]
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:120)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.RuntimeException: org.osgi.framework.BundleException: Bundle org.eclipse.m2e.core.ui cannot be resolved:org.eclipse.m2e.core.ui [115]
  Unresolved requirement: Require-Bundle: org.eclipse.m2e.model.edit; bundle-version="[1.16.0,2.0.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.m2e.model.edit; bundle-version="1.18.2.qualifier"; singleton:="true"
       org.eclipse.m2e.model.edit [116]
         Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.300.v202102110535"; singleton:="true"
              org.eclipse.wst.xml.core [105]
                Unresolved requirement: Require-Bundle: org.eclipse.jem.util; bundle-version="[2.1.200,3.0.0)"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.wst.validation; bundle-version="[1.2.700,1.3.0)"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.wst.common.emfworkbench.integration; bundle-version="[1.2.100,1.3.0)"; resolution:="optional"
                Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"] because it is exposed to package 'org.w3c.dom.events' from resources org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"] and org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"] via two dependency chains.

Chain 1:
  org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.eclipse.core.runtime)(&(bundle-version>=3.14.0)(!(bundle-version>=4.0.0))))
     |
    provide: osgi.wiring.bundle: org.eclipse.core.runtime
  org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"]

Chain 2:
  org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.apache.xerces)(&(bundle-version>=2.12.1)(!(bundle-version>=3.0.0))))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="2.12.1.v20210115-0812"; osgi.wiring.bundle="org.apache.xerces"
  org.apache.xerces [osgi.identity; osgi.identity="org.apache.xerces"; type="osgi.bundle"; version:Version="2.12.1.v20210115-0812"]
    import: (osgi.wiring.package=org.w3c.dom.events)
     |
    export: osgi.wiring.package: org.w3c.dom.events
  org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"]
    at org.eclipse.tycho.core.osgitools.OsgiBundleProject.getResolverState (OsgiBundleProject.java:329)
    at org.eclipse.tycho.core.osgitools.OsgiBundleProject.resolveClassPath (OsgiBundleProject.java:196)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:173)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.lambda$resolveProjects$0 (TychoMavenLifecycleParticipant.java:127)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:183)
    at java.util.stream.WhileOps$1$1.accept (WhileOps.java:99)
    at java.util.ArrayList$ArrayListSpliterator.tryAdvance (ArrayList.java:1631)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:127)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:502)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:488)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:497)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.resolveProjects (TychoMavenLifecycleParticipant.java:158)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:102)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:264)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.osgi.framework.BundleException: Bundle org.eclipse.m2e.core.ui cannot be resolved:org.eclipse.m2e.core.ui [115]
  Unresolved requirement: Require-Bundle: org.eclipse.m2e.model.edit; bundle-version="[1.16.0,2.0.0)"; visibility:="reexport"
    -> Bundle-SymbolicName: org.eclipse.m2e.model.edit; bundle-version="1.18.2.qualifier"; singleton:="true"
       org.eclipse.m2e.model.edit [116]
         Unresolved requirement: Require-Bundle: org.eclipse.wst.xml.core; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.wst.xml.core; bundle-version="1.2.300.v202102110535"; singleton:="true"
              org.eclipse.wst.xml.core [105]
                Unresolved requirement: Require-Bundle: org.eclipse.jem.util; bundle-version="[2.1.200,3.0.0)"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.wst.validation; bundle-version="[1.2.700,1.3.0)"; resolution:="optional"
                Unresolved requirement: Require-Bundle: org.eclipse.wst.common.emfworkbench.integration; bundle-version="[1.2.100,1.3.0)"; resolution:="optional"
                Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"] because it is exposed to package 'org.w3c.dom.events' from resources org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"] and org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"] via two dependency chains.

Chain 1:
  org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.eclipse.core.runtime)(&(bundle-version>=3.14.0)(!(bundle-version>=4.0.0))))
     |
    provide: osgi.wiring.bundle: org.eclipse.core.runtime
  org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"]

Chain 2:
  org.eclipse.wst.xml.core [osgi.identity; osgi.identity="org.eclipse.wst.xml.core"; type="osgi.bundle"; version:Version="1.2.300.v202102110535"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.apache.xerces)(&(bundle-version>=2.12.1)(!(bundle-version>=3.0.0))))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="2.12.1.v20210115-0812"; osgi.wiring.bundle="org.apache.xerces"
  org.apache.xerces [osgi.identity; osgi.identity="org.apache.xerces"; type="osgi.bundle"; version:Version="2.12.1.v20210115-0812"]
    import: (osgi.wiring.package=org.w3c.dom.events)
     |
    export: osgi.wiring.package: org.w3c.dom.events
  org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"]
    at org.eclipse.tycho.core.osgitools.EquinoxResolver.assertResolved (EquinoxResolver.java:451)
    at org.eclipse.tycho.core.osgitools.EquinoxResolver.newResolvedState (EquinoxResolver.java:134)
    at org.eclipse.tycho.core.osgitools.OsgiBundleProject.getResolverState (OsgiBundleProject.java:326)
    at org.eclipse.tycho.core.osgitools.OsgiBundleProject.resolveClassPath (OsgiBundleProject.java:196)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject (DefaultTychoResolver.java:173)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.lambda$resolveProjects$0 (TychoMavenLifecycleParticipant.java:127)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:183)
    at java.util.stream.WhileOps$1$1.accept (WhileOps.java:99)
    at java.util.ArrayList$ArrayListSpliterator.tryAdvance (ArrayList.java:1631)
    at java.util.stream.ReferencePipeline.forEachWithCancel (ReferencePipeline.java:127)
    at java.util.stream.AbstractPipeline.copyIntoWithCancel (AbstractPipeline.java:502)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:488)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:474)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:497)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.resolveProjects (TychoMavenLifecycleParticipant.java:158)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:102)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:264)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

**Comment by laeubi** [comment]
Seems like a regression from 

- https://github.com/eclipse/tycho/issues/213

I'll propose a patch.

**Comment by laeubi** [comment]
@HannesWell it seems one can "help" the resolver here by adding an explicit import package to the failing module:

```
Import-Package: org.w3c.dom;version="3.0.0",
 org.w3c.dom.events;version="3.0.0"
```

the error seem to be occur more likely if the import is actually an "implicit" one e.g. if a dependency of the project depends on the package `org.w3c.dom.events`.

Example: Bundle A requires Bundle B, Bundle B uses `org.w3c.dom.events` then Bundle A fails, now adding `org.w3c.dom.events` to the import of Bundle A make the resolve suceed.

@bjhargrave does this observation help to narrow down the issue and maybe provide a solution in equinox/felix resolver to make it more robust? You already mentioned it might be related to system packages, as `org.w3c.dom.events` was previously provided by java but now becomes more and more a bundle exposing the API it might be interfere here?

**Comment by laeubi** [comment]
This is an example for the found chains that illustrate the problem:
```
Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource some.bundle [osgi.identity; osgi.identity="some.bundle"; type="osgi.bundle"; version:Version="1.0.0.qualifier"; singleton:="true"] because it is exposed to package 'org.w3c.dom.events' from resources org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"] and org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"] via two dependency chains.
Chain 1:
  some.bundle [osgi.identity; osgi.identity="some.bundle"; type="osgi.bundle"; version:Version="1.0.0.qualifier"; singleton:="true"]
    require: (osgi.wiring.bundle=org.eclipse.core.runtime)
     |
    provide: osgi.wiring.bundle: org.eclipse.core.runtime
  org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"]

Chain 2:
  some.bundle [osgi.identity; osgi.identity="some.bundle"; type="osgi.bundle"; version:Version="1.0.0.qualifier"; singleton:="true"]
    require: (&(osgi.wiring.bundle=org.apache.poi.ooxml)(bundle-version>=3.9.0))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="4.1.1.v20200820-1148"; osgi.wiring.bundle="org.apache.poi.ooxml"
  org.apache.poi.ooxml [osgi.identity; osgi.identity="org.apache.poi.ooxml"; type="osgi.bundle"; version:Version="4.1.1.v20200820-1148"]
    import: (osgi.wiring.package=org.w3c.dom.events)
     |
    export: osgi.wiring.package: org.w3c.dom.events
  org.w3c.dom.events [osgi.identity; osgi.identity="org.w3c.dom.events"; type="osgi.bundle"; version:Version="3.0.0.draft20060413_v201105210656"]
	at org.eclipse.tycho.core.osgitools.EquinoxResolver.assertResolved(EquinoxResolver.java:451)
	at org.eclipse.tycho.core.osgitools.EquinoxResolver.newResolvedState(EquinoxResolver.java:134)
	at org.eclipse.tycho.core.osgitools.OsgiBundleProject.getResolverState(OsgiBundleProject.java:326)
	... 30 more
```

@bjhargrave is tycho doing something wrong here or can help the resolver?

One can see here that package `org.w3c.dom.events` is avaiable from `org.eclipse.osgi/3.17.0.v20210823-1805` as well as `org.w3c.dom.events/3.0.0.draft20060413_v201105210656` as soon as I add the package imports, the module resolves without a problem.

**Comment by mickaelistria** [comment]
org.w3c.dom.events in org.eclipse.osgi is actually the one coming from the execution environment.
What I find confusing here is
```
provide: osgi.wiring.bundle: org.eclipse.core.runtime
  org.eclipse.osgi [osgi.identity; osgi.identity="org.eclipse.osgi"; type="osgi.bundle"; version:Version="3.17.0.v20210823-1805"; singleton:="true"]
```
Just like if the org.eclipse.osgi bundle were actually providing the org.eclipse.core.runtime bundle...

**Comment by bjhargrave** [comment]
> Just like if the org.eclipse.osgi bundle were actually providing the org.eclipse.core.runtime bundle...

From some insane reason, the org.eclipse.core.runtime bundle Require-Bundles org.eclipse.osgi and reexports it!

https://git.eclipse.org/c/platform/eclipse.platform.runtime.git/tree/bundles/org.eclipse.core.runtime/META-INF/MANIFEST.MF#n12

I am frankly surprised the resolver can do anything with the web of Require-Bundles in Eclipse. :-)

I try my very hardest to avoid using Require-Bundle. The eclipse plugins for Bndtools do not use Require-Bundle to wire to the Eclipse APIs they use because of the mess. We always use Import-Package with the bundle-symbolic-name attribute to deal with the vast amount of split-packages in the Eclipse API.

https://github.com/bndtools/bnd/blob/5d7f27c4a49e1fe619cab04d8788a6c3aced559e/cnf/includes/bndtools.bnd#L5-L9

**Comment by laeubi** [comment]
> From some insane reason, the org.eclipse.core.runtime bundle Require-Bundles org.eclipse.osgi and reexports it!

org.eclipse.core.runtime a mess but because it is so deeply involved also hard to change :-\ I think it also participates in split-packages (what are another source of mess as well)...

**Comment by HannesWell** [comment]
Thank you Christoph for taking care of this!
