### ISSUE TITLE
NullPointer when validating on pom-Dependencies with parent version in tagetplatform

### ISSUE THREAD

**Issue by EaseRider** [eclipse/tycho#537]
When testing Tycho 2.6.0-SNAPSHOT i ran onto a small error. The pom dependency has its version set by the parent. E.g.:

```  
<parent>
    <groupId>my.bundles</groupId>
    <artifactId>my-bundles</artifactId>
    <version>1.2.3-SNAPSHOT</version>
  </parent>

  <artifactId>thirdparty-bundles</artifactId>
  <packaging>pom</packaging>
```

Either way this feature looks very good and usefull to us.

### Workaround
Add fixed version in pom

```
  <artifactId>thirdparty-bundles</artifactId>
  <version>1.2.3-SNAPSHOT</version>
  <packaging>pom</packaging>
```

### Stacktrace and some details
The MavenModelFacade model has a version null in org.eclipse.tycho.p2.resolver.FeatureGenerator#generatePomFeature
Maybe something needs to be done to propagate the version from its parent(s)

```
java.lang.NullPointerException
        at org.eclipse.tycho.p2.resolver.WrappedArtifact.createOSGiVersionFromMaven(WrappedArtifact.java:190)
        at org.eclipse.tycho.p2.resolver.FeatureGenerator.generatePomFeature(FeatureGenerator.java:150)
        at org.eclipse.tycho.p2.resolver.MavenTargetDefinitionContent.<init>(MavenTargetDefinitionContent.java:299)
        at org.eclipse.tycho.p2.target.TargetDefinitionResolver.resolveContentWithExceptions(TargetDefinitionResolver.java:184)
        at org.eclipse.tycho.p2.target.TargetDefinitionResolver.resolveContent(TargetDefinitionResolver.java:109)
        at org.eclipse.tycho.p2.target.TargetDefinitionResolverService.resolveFromArguments(TargetDefinitionResolverService.java:86)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at org.eclipse.tycho.p2.target.TargetDefinitionResolverService.getTargetDefinitionContent(TargetDefinitionResolverService.java:59)
        at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.resolveTargetDefinitions(TargetPlatformFactoryImpl.java:209)
        at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:161)
        at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:134)
        at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveMetadata(P2ResolverImpl.java:174)
        at org.eclipse.tycho.extras.tpvalidator.TPValidationMojo.validateTarget(TPValidationMojo.java:223)
        at org.eclipse.tycho.extras.tpvalidator.TPValidationMojo.execute(TPValidationMojo.java:152)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)
```

**Comment by laeubi** [comment]
can you share a small reproducer, best would be in the form of an [integration-test](https://github.com/eclipse/tycho/wiki#providing-an-integration-test).

**Comment by laeubi** [comment]
@EaseRider we are about to release 2.7 and I'd like to fix this there, do you think you can share additional details?

**Comment by laeubi** [comment]
> The pom dependency has its version set by the parent

I think you mean that the version is inherited from its parent pom reference? So in this case it should actually be `1.2.3-SNAPSHOT`?

**Comment by EaseRider** [comment]
@laeubi 
Sorry, for not responding. Yes exactly, the version is supposed to come from the parent. Or even parents parent. Thank you for looking into it.
