### ISSUE TITLE
Resolution problem with org.eclipse.core.net

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse/tycho#81]
We are trying latest version(2.4.0-SNAPSHOT) of Tycho in our build.

We are getting the following errors while running surefire tests

!ENTRY org.eclipse.ecf.provider.filetransfer 4 0 2021-04-20 07:55:30.072
!MESSAGE org.eclipse.core.runtime.Status[plugin=org.eclipse.ecf.provider.filetransfer;code=4;message=Warning: Platform proxy API not available;severity2;exception=java.lang.NoClassDefFoundError: org/eclipse/core/net/proxy/IProxyService;children=[]]
!STACK 0
java.lang.NoClassDefFoundError: org/eclipse/core/net/proxy/IProxyService
	at org.eclipse.ecf.provider.filetransfer.retrieve.AbstractRetrieveFileTransfer.setupProxies(AbstractRetrieveFileTransfer.java:956)
	at org.eclipse.ecf.provider.filetransfer.retrieve.AbstractRetrieveFileTransfer.sendRetrieveRequest(AbstractRetrieveFileTransfer.java:886)
	at org.eclipse.ecf.provider.filetransfer.retrieve.MultiProtocolRetrieveAdapter.sendRetrieveRequest(MultiProtocolRetrieveAdapter.java:148)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.sendRetrieveRequest(FileReader.java:454)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.readInto(FileReader.java:384)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:107)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:166)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.handleRemoteIndexFile(AbstractRepositoryManager.java:730)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadIndexFile(AbstractRepositoryManager.java:724)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:666)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:105)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.getQueryableMetadata(P2TargetUtils.java:976)
	at org.eclipse.pde.internal.core.target.IUBundleContainer.getRootIUs(IUBundleContainer.java:766)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.getRootIUs(P2TargetUtils.java:1439)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.resolveWithPlanner(P2TargetUtils.java:1003)
	at org.eclipse.pde.internal.core.target.P2TargetUtils.synchronize(P2TargetUtils.java:827)
	at org.eclipse.pde.internal.core.target.TargetDefinition.resolve(TargetDefinition.java:403)
	at org.eclipse.pde.api.tools.internal.ApiAnalysisApplication.setBaseline(ApiAnalysisApplication.java:247)
	at org.eclipse.pde.api.tools.internal.ApiAnalysisApplication.start(ApiAnalysisApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.equinox.internal.app.AnyThreadAppLauncher.run(AnyThreadAppLauncher.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.net.proxy.IProxyService cannot be found by org.eclipse.ecf.provider.filetransfer_3.2.601.v20201025-0700
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:519)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 23 more

This particular service is provided by https://download.eclipse.org/eclipse/updates/4.20-I-builds/I20210418-1800/plugins/org.eclipse.core.net.linux.x86_64_1.2.400.v20190924-1023.jar

There is a problem in resolving this.

Job link https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Gerrit/4521/

.log file: https://bugs.eclipse.org/bugs/attachment.cgi?id=286173

**Comment by laeubi** [comment]
@sravanlakkimsetti can this be in a smaller context with a reproducer?

If you have the chance to execute this locally, Tycho 2.4.0 SNAPSHOT contains an option 'printBundles' that could reveal if the bundle is missing in the test runtime.

**Comment by mickaelistria** [comment]
@sravanlakkimsetti This doesn't seem to be happening in the context of surefire tests, but in the context of the API check. The API check stuff is not provided by Tycho, so I don't think it's a bug in Tycho.

**Comment by mickaelistria** [comment]
One small reproducer is to build a small Platform bundle, such as org.eclipse.text.quicksearch. From the eclipse.platform.text repo, run `mvn -pl org.eclipse.text.quicksearch clean verify -Pbuild-individual-bundles,api-check`
I'm currently trying several variations of Tycho versions and Eclipse versions.

**Comment by mickaelistria** [comment]
@sravanlakkimsetti I can reproduce this issue with Tycho 2.3 and 2.4.0-SNAPSHOT, and using Eclipse 4.19 and 4.20-I-Builds as comparator. Other cases I see of tycho-eclipserun-plugin being used are working fine. I don't think this issue is a regression in Tycho, nor that it's caused Tycho, but it's more related to some configuration of the eclipse-run step. I'm closing it. Please add me as CC of the issue on Platform side.
