### ISSUE TITLE
Bug 571065 - Multiple Execution block for tycho-p2-extras-plugin causing Error during mirroring

### ISSUE THREAD

**Issue by arunkmadhavan88** [eclipse/tycho#84]
See: https://bugs.eclipse.org/bugs/show_bug.cgi?id=571065
The below error is visible in Tycho 2.4.0-SNAPSHOT as well. Could you please conisder this on priority.

While adding multiple execution block for mirroring p2 update sites separately, the maven build is getting failed with below error. Is there any possibility that we can mirror two separate p2 sites without actually combing them?
I have attached the pom file snippet for your reference.

[MinimalPom.xml](https://github.com/eclipse/tycho/files/6343701/pom.txt)

`[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:2.2.0:mirror (artifcatid) on project Projectname: Error during mirroring: Mirroring failed: Unable to read repository at mvn:groupid:artifactId:20.5.300.30:zip/content.xml. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:2.2.0:mirror Error during mirroring
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error during mirroring
	at org.eclipse.tycho.plugins.p2.extras.MirrorMojo.execute(MirrorMojo.java:263)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	... 20 more
Caused by: org.eclipse.tycho.p2.tools.FacadeException: Mirroring failed: Unable to read repository at mvn:groupid:artifactId:20.5.300.30:zip/content.xml.
	at org.eclipse.tycho.p2.tools.mirroring.MirrorApplicationServiceImpl.mirrorStandalone(MirrorApplicationServiceImpl.java:82)
	at org.eclipse.tycho.plugins.p2.extras.MirrorMojo.execute(MirrorMojo.java:260)
	... 22 more
Caused by: org.eclipse.equinox.p2.core.ProvisionException: Unable to read repository at mvn:groupid:artifactId:20.5.300.30:zip/content.xml.
	at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:247)
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.getLocalFile(SimpleMetadataRepositoryFactory.java:69)
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:89)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:63)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:775)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:676)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:110)
	at org.eclipse.equinox.p2.internal.repository.tools.AbstractApplication.addRepository(AbstractApplication.java:143)
	at org.eclipse.equinox.p2.internal.repository.tools.AbstractApplication.initializeRepos(AbstractApplication.java:124)
	at org.eclipse.equinox.p2.internal.repository.tools.MirrorApplication.run(MirrorApplication.java:196)
	at org.eclipse.tycho.p2.tools.mirroring.MirrorApplicationServiceImpl.mirrorStandalone(MirrorApplicationServiceImpl.java:78)
	... 23 more
Caused by: java.lang.NullPointerException
	at org.eclipse.tycho.osgi.configuration.MavenDependenciesResolverConfigurer.resolve(MavenDependenciesResolverConfigurer.java:61)
	at org.eclipse.tycho.osgi.configuration.MavenProtocolHandler$MavenURLConnection.connect(MavenProtocolHandler.java:96)
	at org.eclipse.tycho.osgi.configuration.MavenProtocolHandler$MavenURLConnection.getInputStream(MavenProtocolHandler.java:110)
	at org.eclipse.ecf.provider.filetransfer.browse.URLFileSystemBrowser.runRequest(URLFileSystemBrowser.java:120)
	at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:71)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:`

**Comment by laeubi** [comment]
> Could you please conisder this on priority

At least you have the following options to give more priority on this this:

- Provide a small (executable) reproducer that shows your problem in form of a github repo, even better provide an itest showing your problem see https://github.com/eclipse/tycho/tree/master/tycho-its
- Provide a patch that fixes the problem, its all open source and everyone is encourage to participate!
- You can always contact me (or search for someone else with java skills) and offer a funding for a feature or bug-fix if you need enterprise-support

**Comment by arunkmadhavan88** [comment]
Hi @laeubi 

Thanks for your reply.
Please find the zip containing the project with launch files: 
[mirror-gav-p2.zip](https://github.com/eclipse/tycho/files/6343871/mirror-gav-p2.zip)

Hope this will suffice to troubleshoot further.

**Comment by laeubi** [comment]
Just to make sure: Does this works with "plain" updatesites? What is the usecase here to mirror an already zipped site (in contrast of just download and extract it?)

**Comment by arunkmadhavan88** [comment]
@laeubi 
Our project is moving to Nexus 3 and this is not supporting the unzip plugins. Tycho version: 2.2.0 already helped us during the maven build. But for local development it still needs repositories in unzipped format. If we are able to handle this via mirroring in seprate folders, we will just have to adjust the target platforms accordingly without much changes. At the same time we could completely avoid the dependency over nexus2 (the older version which supports unzip). Combining all updatesite into a single mirror also not suits within our current project.

**Comment by laeubi** [comment]
If you are using recent eclipse+m2e you can use the 'mvn:org.eclipse.january:org.eclipse.january.releng.p2:2.3.0:zip' in the target platform directly, you can even use this target in tycho then so there is no need to play around with mirroring/unpacking and so on.

**Comment by arunkmadhavan88** [comment]
@laeubi 
Did you mean the format: 'mvn:org.eclipse.january:org.eclipse.january.releng.p2:2.3.0:zip' is supported for target definition file created from eclipse or inside the maven pom? Our developers rely on using the target definition file to load the update sites for eclispe plugin development. We do not usually rely on maven build for local launches, as it is time consuming. Instead everything is defined within the target definition file and loaded at once. Once the local launches are working fine, we will go for the maven build to create the package and deploy.

**Comment by laeubi** [comment]
![grafik](https://user-images.githubusercontent.com/1331477/115410721-25e7b880-a1f3-11eb-9518-9512ec2a55b8.png)

**Comment by laeubi** [comment]
You can use the same target file for your developers and for your tycho build and both can use mvn: URLs.

**Comment by arunkmadhavan88** [comment]
@laeubi 
Exactly this is what we were expecting!!. Thanks alot and we will come back to you asap.
But thank you again for providing the screenshot :-)
